# Generated by Django 3.1.3 on 2020-12-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('courseID', models.IntegerField(default=0, max_length=5, primary_key=True, serialize=False)),
                ('instructor', models.CharField(blank=True, default='', max_length=60)),
                ('duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
            ],
        ),
    ]
