# Generated by Django 3.1.3 on 2020-11-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(choices=[('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss')], max_length=60)),
                ('first_name', models.CharField(default='', max_length=60)),
                ('last_name', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
