# Generated by Django 3.1.3 on 2020-11-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='suffix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], max_length=60),
        ),
    ]
