# Generated by Django 3.1.3 on 2020-11-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201124_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='suffix',
            field=models.CharField(choices=[('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Miss', 'Miss'), ('Ms.', 'Ms.')], max_length=60),
        ),
    ]
