# Generated by Django 3.1.3 on 2020-11-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201124_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='suffix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Miss', 'Miss'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], max_length=60),
        ),
    ]
