# Generated by Django 3.1.3 on 2020-11-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201124_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('drinks', 'drinks'), ('appetizers', 'appetizers'), ('treats', 'treats'), ('entrees', 'entrees')], max_length=60),
        ),
    ]
